### ISSUE TITLE
希望加入答题卡功能

### ISSUE THREAD

**Issue by mlb0925** [Okysu/cslg-ideology#1]
希望加入答题卡功能 这样更方便一点 谢谢 能加入左右滑题更好了

**Comment by Okysu** [comment]
好的，我将在今天下午尝试更新一下。

**Comment by Okysu** [comment]
这次更新的会有点多，稍微等待一下

**Comment by Okysu** [comment]
已更新至：[4af04a7dbb08c453ac7e4f4a8d18d736fbbc19ef]

**Comment by mlb0925** [comment]
谢谢，我等一会试下
